language: go
go_import_path: github.com/heptio/authenticator
go:
  - 1.9.x

sudo: required

services:
  - docker

install:
  - curl -s -L -o /tmp/goreleaser.tgz https://github.com/goreleaser/goreleaser/releases/download/v0.45.1/goreleaser_Linux_x86_64.tar.gz
  - tar -xzvf /tmp/goreleaser.tgz -C /tmp/
  - sudo mv /tmp/goreleaser /usr/local/bin

script:
  - make test build

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: oS+D/347++stAEosfFt4ElsvVkdUZ7Vt/lpAssoR3wMlUFpDyyZYSQEBnA5Ml9997/UhjezhtBjcVoK41Jwuh78AVihjzk0xD7RhM5mqDhcbacT0nA6NUjPI88yhwkM0LBZSK46cBO4g2OioW5iE1SO7v//7UKtr/XGZNxCupXSBLJ8RwWpYoukHaYxsiWJGd6AnO4WhGbjxGrKBemkCMYwGrFHvRkQM/WMEZsdoZgkHuyVGMCJcbP4E7CGSyPD4pcVp2/3eNlULVqwPJYXtGC7XK8gWMzR77elYagVZz63XbaYt18M+hKhRCBr3wghkf5sSAoSPM5W+bsyFc8dTCdq9u+qRa3ep0SD0zHC9j7PT+wetoGOH4C83TxOF5wdX6zyOaxQQW/Br8rhHwE6ISHWDoxR2cLRfnokA45zWtOJSwvJpmvHsuZzM3+VKE9jhS4Ctac0cIUdCHyz8okfnnW57B/ve0jTHt0zyuLmsf/FdOHXNJhJN8kPdfuWROwj+pwc7sHS8YpejUmemjqXv9k+i8xmk0INOgTzpykXNk4XECLHHjcIcdjnesRJsIePiSYN5pmlboPbM5kVEQYoYGBY2UTewl9kWAsxGtgQwHEjcxDuTxzjVTU2PyT+RswZmekfcorED6nORS4U8oPnZwNabSwVm6pjMGgl7l9VQehM=
  file:
  - dist/windowsamd64/heptio-authenticator-aws.exe
  - dist/linuxamd64/heptio-authenticator-aws
  - dist/darwinamd64/heptio-authenticator-aws
  on:
    repo: seanturner83/authenticator
    all_branches: true
